# Generated by Django 3.2.9 on 2021-12-04 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20211204_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='defaultGooglePhotoUrl',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
